### ISSUE TITLE
Not able to confirm health mode status

### ISSUE THREAD

**Issue by SV-stark** [maxco2/acer-battery-wmi#1]
Not able to confirm health mode status
>cat health_mode 
>cat: health_mode: No such device

and 
>sudo echo 1 >> health_mode
>zsh: permission denied: health_mode

No text editor including vim and nano can open the file.

**Comment by maxco2** [comment]
Please confirm that you have a matching WMI method on your device.

The output of the following command should contain the WMI GUID [9772EC5-04B1-4BFD-843C-61E7F77B6CC9](https://github.com/maxco2/acer-battery-wmi/blob/master/src/acer_battery_wmi.c#L15)
```bash
 sudo fwts wmi -
```


Ref:
https://wiki.ubuntu.com/Kernel/Reference/WMI

**Comment by SV-stark** [comment]
Terribly sorry that I forgot to mention that I am using Manjaro. Is there any other way to get this WMI GUID?

**Comment by maxco2** [comment]
> Terribly sorry that I forgot to mention that I am using Manjaro. Is there any other way to get this WMI GUID?

`fwts-git` is in AUR.

**Comment by SV-stark** [comment]
Thanks for the directions. here is the excerpt matching the GUID 
> SB_.PCI0.WMID._WDG (3 of 12)
>  GUID: 79772EC5-04B1-4BFD-843C-61E7F77B6CC9
>   WMI Method:
>     Flags          : 0x02 (Method)
>     Object ID      : BE
 >    Instance       : 0x01
> PASSED: Test 1, 79772EC5-04B1-4BFD-843C-61E7F77B6CC9 has associated method
>  \_SB_.PCI0.WMID.WMBE

**Comment by SV-stark** [comment]
Thanks for directions. I didn't see the GUID you mentioned, but I did see a match _79772EC5-04B1-4BFD-843C-61E7F77B6CC9_  which I suppose is of no use. 
 Also additionally me laptop is Acer Aspire A515-51G (UN.GWJSI.006)

**Comment by maxco2** [comment]
I'm not sure if this GUID is battery health control. Please be careful.

**Comment by rybomir** [comment]
Hey @maxco2, I'm facing a similar issue - I've found a match for 79772EC6-04B1-4BFD-843C-61E7F77B6CC9, which seems to differ by one digit from @SV-stark's. Echoing health_mode doesn't seem to have any effect, it stays empty. I'm on Aspire VX5-591G-58TC.

However, I've noticed that you probably made a typo:
> The output of the following command should contain the WMI GUID [9772EC5-04B1-4BFD-843C-61E7F77B6CC9](https://github.com/maxco2/acer-battery-wmi/blob/master/src/acer_battery_wmi.c#L15)

In reality acer_battery_wmi.c contains 79772EC5-04B1-4BFD-843C-61E7F77B6CC9, so... It should have worked for @SV-stark? Unless I'm missing something obvious here. 

PS. Output of `sudo fwts wmi -` :
> Low failures: 1
 wmi: GUID 79772EC6-04B1-4BFD-843C-61E7F77B6CC9 should have an associated method WMBF defined, however this does not seem to exist.

**Comment by maxco2** [comment]
@rybomir Sorry for not getting back to you sooner. My laptop "fwts" is also output  79772EC6-04B1-4BFD-843C-61E7F77B6CC9 which is not the battery health control GUID. If you have a Windows system, maybe you can do some reverse engineering on Acer Care Center which is written in C#.
![image](https://user-images.githubusercontent.com/11772699/227402132-184285fe-b2f2-4ece-8e89-e656031c13c6.png)

**Comment by rybomir** [comment]
@maxco2 Ok, so, curious thing - since my last comment I've reinstalled the OS (EndeavourOS before, Fedora now), and it looks like the correct GUID just... appeared?

![image](https://user-images.githubusercontent.com/50298853/227583686-9e5674a9-c0f7-4e7e-aa74-6a18c55be798.png)

However, this didn't resolve anything, echoing health_mode with "1" still doesn't have any effect. Any ideas?

`dmesg` output after echoing:
```
[   45.041742] Unexpected output format getting battery health status, buffer length:4
[   58.198921] Setting battery health status success! Status was 0 ret was 0x0 (0)
```

**Comment by maxco2** [comment]
@rybomir 

Judging from the dmesg log, setting the battery charging health threshold is successful, but failing to obtain the status. Maybe you can try charging it to see if it works.
