### ISSUE TITLE
Confirming `health_mode` status

### ISSUE THREAD

**Issue by repinger** [maxco2/acer-battery-wmi#2]
Hi,

I was wondering whether `health_mode` is working on my laptop (SF314-54G; Linux version 6.1.0-arch1-1) or not. This is the output from `dmesg`:

```
[ 5645.990258] Setting battery health status success! Status was 0 ret was 0x1 (1)
```

**Comment by maxco2** [comment]
A quick way to confirm is that if your power is above 80%, it should be in the discharge state now, if it is below 80%, it will charge to 80% and stop.
