### ISSUE TITLE
For Arch Linux (Garuda) "PKGBUILD does not exist" Error

### ISSUE THREAD

**Issue by linuxtopia** [maxco2/acer-battery-wmi#3]
Hello,

I cannot install and use acer-battery-dkms due to the error.

`PKGBUILD does not exist`

`'acer-battery-wmi-0.1-1-x86_64.pkg.tar.zst': could not find or read package`

**Comment by maxco2** [comment]
Please confirm that you clone https://github.com/maxco2/acer-battery-wmi-dkms.git correctly.

**Comment by linuxtopia** [comment]
it worked now.
